name: Docker Image CI test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: cd ./docker-php-fpm-8.1 && make build REPOSITORY_NAME=mrlexx
