name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    # Update references
    - name: checkout all the submodules
      uses: actions/checkout@v4
      with:
        submodules: recursive    
        
    - uses: actions/checkout@v4
    - name: Build the Docker image
      # run: docker build . --file ./docker-php-fpm-8.1/Dockerfiles/Dockerfile --tag mrlexx/php-fpm-8.1
      run: cd ./docker-php-fpm-8.1 && make build REPOSITORY_NAME=mrlexx
