name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - 
      name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - 
      name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive    

    - 
      name: Build the Docker image
      run: cd ./docker-php-fpm-8.1 && make build REPOSITORY_NAME=mrlexx
